version: "3.7"
services:
  app:
    build:
      args:
        user: ${DOCKER_USER}
        uid: ${DOCKER_UID}
      context: ./
      dockerfile: Dockerfile
    image: ${DOCKER_IMAGE_NAME}
    container_name: ${DOCKER_APP_CONTAINER_NAME}
    restart: unless-stopped
    working_dir: /var/www/
    volumes:
      - ./:/var/www
    networks:
      - default
  db:
    image: mysql:5.7
    container_name: ${DOCKER_DB_CONTAINER_NAME}
    restart: unless-stopped
    environment:
      MYSQL_DATABASE: ${DB_DATABASE}
      MYSQL_ROOT_PASSWORD: ${DB_ROOT_PASSWORD}
      MYSQL_PASSWORD: ${DB_PASSWORD}
      MYSQL_USER: ${DB_USERNAME}
      SERVICE_TAGS: dev
      SERVICE_NAME: mysql
    ports:
      - ${DOCKER_DB_EXPOSED_PORT}:3306
    volumes:
      - ./docker-compose/mysql:/docker-entrypoint-initdb.d
    networks:
      - default

  server:
    image: nginx:alpine
    container_name: ${DOCKER_SERVER_CONTAINER_NAME}
    restart: unless-stopped
    ports:
      - ${DOCKER_SERVER_EXPOSED_PORT}:80
    volumes:
      - ./:/var/www
      - ./docker-compose/nginx:/etc/nginx/conf.d/
    networks:
      - default

networks:
  default:
    external:
      name: ${DOCKER_NETWORK_NAME}
